# Generated by Django 3.2.5 on 2021-07-26 00:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dias', models.IntegerField()),
            ],
            managers=[
                ('tours', django.db.models.manager.Manager()),
            ],
        ),
    ]
